// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'use FlutterFire CLI to configure web for pco-app-3d42d.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJf08_uax0vrI5-sKvL_2m2DWq59iPdZc',
    appId: '1:906367301565:android:08dc80b3e57222051944d4',
    messagingSenderId: '906367301565',
    projectId: 'pco-app-3d42d',
    storageBucket: 'pco-app-3d42d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI35oPKdygiZSArt5TJdA6ICP4rbBqAco',
    appId: '1:906367301565:ios:845f299e91ae6a551944d4',
    messagingSenderId: '906367301565',
    projectId: 'pco-app-3d42d',
    storageBucket: 'pco-app-3d42d.firebasestorage.app',
    androidClientId: '906367301565-hh59gc4j68ii464ob22pf3oqd1k12h51.apps.googleusercontent.com',
    iosClientId: '906367301565-u8itonvvbjlbvttft2un9fgb0un3j54v.apps.googleusercontent.com',
    iosBundleId: 'com.pcobh.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI35oPKdygiZSArt5TJdA6ICP4rbBqAco',
    appId: '1:906367301565:ios:845f299e91ae6a551944d4',
    messagingSenderId: '906367301565',
    projectId: 'pco-app-3d42d',
    storageBucket: 'pco-app-3d42d.firebasestorage.app',
    androidClientId: '906367301565-hh59gc4j68ii464ob22pf3oqd1k12h51.apps.googleusercontent.com',
    iosClientId: '906367301565-u8itonvvbjlbvttft2un9fgb0un3j54v.apps.googleusercontent.com',
    iosBundleId: 'com.pcobh.app',
  );

}
