// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnekGgn1hc9epIWmeAeZpUtdUbnkoiXpk',
    appId: '1:1019530614766:web:9825a07719b93e6b4da0ff',
    messagingSenderId: '1019530614766',
    projectId: 'shoorapp-61239',
    authDomain: 'shoorapp-61239.firebaseapp.com',
    storageBucket: 'shoorapp-61239.firebasestorage.app',
    measurementId: 'G-WRZPQMBSL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAihhBU41DGXpDrioRFxaXrS9j87HDYAdo',
    appId: '1:1019530614766:android:5f287354bf1434e44da0ff',
    messagingSenderId: '1019530614766',
    projectId: 'shoorapp-61239',
    storageBucket: 'shoorapp-61239.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWEVQiyt2rta481lGtLSl861ZKJ6kCruQ',
    appId: '1:1019530614766:ios:9c0583d560badc5e4da0ff',
    messagingSenderId: '1019530614766',
    projectId: 'shoorapp-61239',
    storageBucket: 'shoorapp-61239.firebasestorage.app',
    androidClientId: '1019530614766-3v3hgebu3tbtga2h014j29l9f36k6f9a.apps.googleusercontent.com',
    iosClientId: '1019530614766-tq2sb46p1pn2ch8ipi9ngv7rl4mco19d.apps.googleusercontent.com',
    iosBundleId: 'com.shoor.shoorapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWEVQiyt2rta481lGtLSl861ZKJ6kCruQ',
    appId: '1:1019530614766:ios:9c0583d560badc5e4da0ff',
    messagingSenderId: '1019530614766',
    projectId: 'shoorapp-61239',
    storageBucket: 'shoorapp-61239.firebasestorage.app',
    androidClientId: '1019530614766-3v3hgebu3tbtga2h014j29l9f36k6f9a.apps.googleusercontent.com',
    iosClientId: '1019530614766-tq2sb46p1pn2ch8ipi9ngv7rl4mco19d.apps.googleusercontent.com',
    iosBundleId: 'com.shoor.shoorapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnekGgn1hc9epIWmeAeZpUtdUbnkoiXpk',
    appId: '1:1019530614766:web:572a6b656bd1c3bb4da0ff',
    messagingSenderId: '1019530614766',
    projectId: 'shoorapp-61239',
    authDomain: 'shoorapp-61239.firebaseapp.com',
    storageBucket: 'shoorapp-61239.firebasestorage.app',
    measurementId: 'G-NK1YT9CTDT',
  );

}